# Add this block to /etc/nginx/sites-enabled/crm-frontend
# Inside the server {} block for crm.acicdf.org.br

location /associe-se/ {
    root /var/www/crm-frontend;
    try_files $uri $uri/ /associe-se/index.html;
}
